### ISSUE TITLE
Multiple linkings

### ISSUE THREAD

**Issue by jadamec** [dingo-d/simple-linked-variations-for-woocommerce#7]
Hi there,
what about to add multiple linkings? One is terribly not enough for todays eshops. Thanks!

**Comment by dingo-d** [comment]
Hi,

This is on my 'to do' list, but as this plugin is not something I'm making money of off, it's not top on my priority list.
One day, when I'll have more time I'll try to work on it, but as it stands now I cannot make any promises if and when that would be.
